# 异常

​	异常Exception，抛出异常后程序会崩溃退出，之后的代码不再执行。

​	可以通过异常处理机制来解决该问题。

* 对于可能出错的代码块，可以使用`try-catch`异常处理机制包裹：

  * 包裹快捷键：选中被包裹代码->`ctrl+alt+t`->选择。
  * 进行异常处理后，程序即使出现异常也可以继续执行。

* 异常事件可分为两大类：

  * Error错误：

    JVM无法解决的严重问题，程序必须崩溃。
  
    比如StackOverflow，OutOfMemory。
  
  * Exception：
  
    一般性问题，可以使用针对性代码进行处理。
  
    比如空指针访问、试图读取不存在的文件、网络中断等。
  
    又分为运行时异常和编译时异常。

### 异常体系图

* Throwable：异常的根类。

  * Error：

    * StackOverflowError
    * OutOfMemoryError
    * 各种Error...

  * Exception：

    * RuntimeException ：运行时异常。编译器不要求强制处理的异常，一般指编程的逻辑错误。
      * NullPointerException：空指针异常
      * ArithmeticException：算数异常
      * ArrayIndexOutofBoundsException：数组索引越界异常
      * ClassCastException：类型异常
      * NumberFormatException：数字格式异常

    * 其他编译时异常：编译时异常编译器要求必须处理。

### 常见运行时异常

#### NullPointerException

​	空指针异常，程序在需要使用对象的地方为null。

#### ArithmeticException

​	算术异常。出现异常条件时抛出，比如除以0。

#### ArrayIndexOutOfBoundsException

​	数组下标越界异常。使用非法索引访问数组时抛出，比如索引为负或>=数组的length。

#### ClassCastException

​	类型转换异常。当试图将对象强制转换为不是实例的子类时抛出。

#### NumberFormatException

​	数字格式不正确异常。试图将字符串转换、但字符串不能转换成适当格式时抛出。比如试图将hello用Integer.parseInt进行转换。

### 异常处理机制

​	异常处理就是当异常发生时，对异常处理的方式。

```java
try {

}catch (Exception e) {

}finally {
	/*可选*/
}
```

#### try-catch-finally

​	在代码中捕获发生的异常，自行处理。

* try代码块中当异常发生时，异常后面的代码不会执行，直接进入catch块。

* try代码块中当异常发生时，系统将异常封装成Exception对象，传递给catch块。

  得到异常对象后，程序员自行处理。

* catch块中可以通过`e.getMessage()`方法来得到异常信息。

* 不管是否有异常发生，都会执行finally代码块。

  通常将释放资源的代码放在finally中。

* 如果没有发生异常，catch块不会执行。

* 可以通过多个catch语句捕获不同的异常，要求，子类异常在前，父类异常在后。

  ```java
  try {
              String name = null;
              System.out.println(name.length());
              name = "hello";
              Integer.parseInt(name);
          } catch (NullPointerException e) {
              System.out.println("空指针异常:" + e.getMessage());
          } catch (NumberFormatException e) {
              System.out.println("数字格式异常:" + e.getMessage());
          } catch (Exception e) {
      		// Exception作为以上两种异常的父类必须放在最后
              System.out.println("异常:" + e.getMessage());
          } finally {
  
          }
  ```

* 特殊情况：

  * finally块中的内容必须执行，如果catch块中有return，则暂时不返回，在执行完finally块后再返回（如果finally块中没有return）。

    ```java
     public static int method() {
            try {
                String name = null;
                name.equals("abc");
            } catch (Exception e) {
                System.out.println("catch");
                return 0;
            } finally {
                return 2;
            }
        }
    	// 该方法返回2
    ```

  * 另一种特殊情况：

    结果：输出`i=3`，返回2。

    ```java
        public static int method() {
            int i = 1;
            try {
                String name = null;
                name.equals("abc");
                return 1;
            } catch (Exception e) {
                System.out.println("catch");
                return ++i;// 这里会用一个临时变量来保存，return不会立即执行。
            } finally {
                i++;// catch块中return的i自增为2后被临时变量保存，因此这里i的自增不会影响到函数返回值。
                System.out.println("i=" + i);
            }
        }
    ```

#### throws

​	将发生的异常抛出，交给调用者来处理，最顶级处理者是JVM。

* JVM处理异常的方式：
  * 输出异常信息。
  * 退出程序。
* 如果没有显式处理异常，默认采取throws。
* 子类重写父类方法时，抛出的异常必须与父类一致，或者是父类异常的子类。

#### 自定义异常

​	当程序出现的错误没有在Throwable子类中描述处理时，可以自己设计异常类描述错误信息。

* 一般都继承RuntimeException，即做成运行时异常。

  因为编译异常编译器会要求修改。

#### throw & throws

* throws用于方法声明处，后跟异常类型（列表），是异常处理的一种方式。

  try-catch一般不和throws同时使用。

* throw用于手动生成异常对象，用于方法体，后跟异常对象。

  ```java
  public class CustomException {
      public static void main(String[] args) {
          int age = 1;
          if (age <= 100 && age >= 20) {
  
          } else {
              throw new MyException("自定义异常");// throw关键字用于方法体内部，表示生成异常对象。
          }
      }
  
      public static void test() throws ArithmeticException,NullPointerException {
  		// throws关键字用于方法声明处，后跟异常类型列表，一般写RuntimeException。
      }
  }
  
  class MyException extends RuntimeException { 
      public MyException(String message) {
          super("自定义异常");
      }
  }
  ```

  
